# Project Information
site_name: Workspace ONE UEM APIs
site_url: https://euc-dev.github.io/ws1-uem-apis
site_author: Phil Helmling
site_description: POC for developer.omnissa.com
docs_dir: docs
site_dir: .site
use_directory_urls: true

# Repository
repo_url: https://github.com/euc-dev/ws1-uem-apis
edit_uri: edit/main/docs/

# Copyright
copyright: |
  Copyright &copy; 2005-2024 Broadcom. All rights reserved.<br/>
  The term “Broadcom” refers to Broadcom Inc. and/or its subsidiaries.<br/><br/>

# Configuration
theme:
  name: material
  favicon: favicon.ico
  logo: assets/images/icon-white.svg
  icon:
    repo: fontawesome/brands/github
    annotation: material/plus-circle
    annotation: material/circle-medium
    annotation: material/record-circle
    annotation: material/arrow-right-circle
    annotation: material/arrow-right-circle-outline
    annotation: material/chevron-right-circle
    annotation: material/star-four-points-circle
    annotation: material/plus-circle-outline
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Dark Theme
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Light Theme
  font:
    text: Roboto
    code: Roboto Mono
  features:
  - content.action.edit
  - content.action.view
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  #- navigation.expand
  - navigation.footer
  - navigation.header
  - navigation.indexes
  - navigation.instant
  #- navigation.path
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow
  #- toc.integrate

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      indexing: 'full'
  - open-in-new-tab
  - markdownextradata:
      jinja_options:
        variable_start_string: "${{"
        variable_end_string: "}}"
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: false
      exclude:
        - index.md
      fallback_to_build_date: true
      type: timeago
  - swagger-ui-tag
  #- neoteroi.mkdocsoad:
  #    use_pymdownx: true

# Customization
extra:
  version:
    default: latest
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/euc-oss/app-volumes-apis
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/WorkspaceONE
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCYgGfqfb9c3AOGJqxqdjNYw
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/vmware-workspaceone/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/vmwareworkspaceone/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/vmware/
    - icon: fontawesome/brands/slack
      link: https://slack.com/vmware
    - icon: fontawesome/brands/discord
      link: https://discord.com/vmware

extra_css:
  - assets/stylesheets/extra.css
  #- ./assets/stylesheets/spanable.css
  #- assets/stylesheets/neoteroi-cards.css
  - assets/stylesheets/neoteroi-mkdocs.css
  #- assets/stylesheets/neoteroi-mkdocs.min.css
  #- assets/stylesheets/neoteroi-mkdocsoad.css
  #- assets/stylesheets/neoteroi-spantable.css

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - neoteroi.spantable
  #- neoteroi.mkdocsoad
  - neoteroi.cards
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
        - material/.icons
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.snippets:
      #check_paths: true
      #base_path: !relative # Relative to the directory of the current Markdown file
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - tables
  - toc:
      permalink: true

# Navigation
# nav:
